config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  namespace :minisite do
    resources :banners
  end

  # omniauth with doorkeeper
  use_doorkeeper do
    skip_controllers :applications
  end

  namespace :auth do
    get '/me' => 'credentials#me'
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  # Custom Errors
  %w( 404 403 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  # APP
  scope :app do

    get '/', to: 'hupe#index'
    get 'dashboards/general', to: 'dashboards#general'



    resources :scaffolds, only: [:index]

    resources :groups

    namespace :people do
      resources :identification_document_types
    end

    namespace :trabajando do
      resources :careers, only: [:show, :edit, :index, :update]
      resources :universities, only: [:show, :edit, :index, :update]
      resources :job_types, only: [:index,:edit, :update, :show]
      resources :software_levels, only: [:index, :show, :edit, :update]
      resources :education_levels, only: [:index, :show, :edit, :update]
      resources :education_states, only: [:index, :show, :edit, :update]
      resources :applicant_profiles, only: [:show, :edit, :index, :update]
      resources :areas, only: [:index, :show, :edit, :update]
      resources :work_days, only: [:show, :edit, :index, :update]
      resources :company_activities, only: [:show, :edit, :index, :update]
      resources :marital_statuses, only: [:show, :edit, :index, :update]
      resources :countries, only: [:show, :edit, :index, :update]
      resources :states, only: [:show, :edit, :index, :update]
      resources :cities, only: [:show, :edit, :index, :update]
    end

    resources :faqs

    # namespace :minisite do
    #   resources :banners
    # end

    resources :generic_attachments, path: :attachment, only: [:destroy] do
      member do
        get :download
      end
    end

    resources :comment, only: [:index, :create]

    namespace :company do
      resources :areas
      resources :marital_statuses
      resources :vacancy_request_reasons
      resources :records
      resources :contract_types
      resources :positions
      resources :business_units
      resources :cencos
      resources :estates
      resources :recruitment_sources
      resources :timetables
      resources :engagement_origins
      resources :recruitment_sources
      resources :white_ruts do
        collection do
          post :upload_white_list
        end
      end
      resources :employees, only: [:index] do
        collection do
          post :upload_load_massive
          get  :download_file_example
        end
      end
      # resources :references, except: [:destroy, :edit, :update] do
      #   member do
      #     get :confirm
      #   end
      # end
    end


    namespace :video_interview do
      resources :questions
      resources :answers, only: [:show, :index]
    end

    namespace :document do
      resources :descriptors
      resources :groups
      resources :records, only: [:destroy]
    end

    namespace :education do
      resources :study_levels
      resources :institutions do
        collection do
          get :custom
        end

        member do
          put :update_custom
          put :approve_custom
        end
      end

      resources :careers
    end

    namespace :tag do
      resources :course_tags, controller: 'base_tags', type: Tag::CourseTag.to_s
      resources :company_position_tags, controller: 'base_tags', type: Tag::CompanyPositionTag.to_s
    end

    namespace :territory do
      resources :cities
    end

    namespace :territory do
      resources :states
    end

    namespace :territory do
      resources :countries
    end

    namespace :stage do
      resources :not_apply_reasons
    end

    namespace :calendar do
      resources :events, only: [:create, :update] do
        member do
          put :update_for_applicants
          put :mark_attended
          put :mark_will_attend
          get :confirm_will_attend
          get :marked_will_attend
        end

        collection do
          post :create_for_applicants
        end
      end
    end

    namespace :applicant do
      resources :profile_types
      resources :software_levels
      resources :bases, only: [:show, :edit] do
        member do
          put :update
          post :enroll
          post :add_degree
          post :comment
          post :notification_update_profile
          get :generate_cv
          post :upload_documents
          get '/download_document/:name', action: :download_document, as: 'download_document'
          post :update_password
        end
        collection do
          get :index, action: :search
          get :search
          post :_search
          post :enroll
          post :send_update_request
          get :generate_massive_cvs
          post :massive_mailer
        end
      end
      resources :externals, only: [:create, :new]
      resources :catcheds, only: [:create, :new, :edit]
    end

    namespace :worker do
      resources :bases, only: [:create,:new, :show, :edit, :update] do
        member do
          post :add_role
        end
        collection do
          get :index, action: :search
          get :search
        end
      end
    end

    namespace :laborum do
      resources :metadata, only: [], defaults: { format: :json } do
        collection do
          get :areas
          get :subareas
          get :denominaciones
          get :frecuencias_pago
          get :denominaciones
          get :direcciones
          get :idiomas
          get :niveles_idiomas
          get :industrias
          get :tipos_trabajo
          get :areas_estudio
          get :estados_estudio
          get :tipos_estudio
          get :paises
          get :regiones
          get :comunas
        end
      end
    end

    namespace :enrollment do
      resources :bases, only: [] do
        member do
          post :discard

          get :mark_invitation_accepted
          get :mark_invitation_rejected

          resources :offer_letters, only: [], param: :offer_letter_id  do
            member do
              get :accept
              get :show_reject
              post :reject
              get :answered
            end
          end
        end

        collection do
          post :invite
          post :dispose
          post :revert_dispose
          post :next_stage
          get :export
          post :unenroll
        end
      end

      resources :discard_reasons do
        member do
          post :set_as_default_when_close_course
          post :toggle_blacklist
        end
      end
    end

    namespace :hiring_request do
      resources :records, except: [:destroy] do
        member do
          put :switch_state
        end
        collection do
          post :_search
        end
      end
    end

    resources :vacancies, only: [] do
      collection do
        put :assign_course
        put :assign_new_course
      end
    end

    namespace :offer do
      resources :letters, only: [] do
        member do
          post :accept
        end
      end
      resources :reject_reasons
    end

    resources :courses, only: [:create, :new, :show, :edit, :update] do
      member do
        resources :course_postulations, only: [:index] do
          collection do
            post :_search
            post :accept
            post :reject
            post :reset
            get :export
          end
        end

        post :_search, action: :_search_candidates

        # Modulo de VideoInterview
        namespace :video_interview, as: :course_video_interview do
          resources :stages, only: [:show], param: :stage_id do
          end
        end
        # Modulo de Promotion
        namespace :promotion, as: :course_promotion do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              post :send_acceptance_email
            end
          end
        end

        # Módulo stage (genérico)
        namespace :stage, as: :course_stage do
          resources :bases, only: [], param: :stage_id do
          end
        end

        # Modulo de manager_interview
        namespace :manager_interview, as: :course_manager_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de skill_interview
        namespace :skill_interview, as: :course_skill_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de assigning_weighting
        namespace :assigning_weighting, as: :course_assigning_weighting do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de internal_postulation
        namespace :internal_postulation, as: :course_internal_postulation do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :records, only: [:create], param: :record_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de test
        namespace :test, as: :course_test do
          resources :stages, only: [:show, :index], param: :stage_id do

app/models/trabajando.rb
module Trabajando
  def self.table_name_prefix
    'trabajando_'
  end
end

app/models/trabajando/applicant_profile.rb
class Trabajando::ApplicantProfile < ActiveRecord::Base
  has_many :publications,
           class: Trabajando::Publication,
           foreign_key: :applicant_profile_id

  belongs_to :hupe_profile_type, class: Applicant::ProfileType
  validates :name, presence: true, uniqueness: true
  validates :trabajando_id, presence: true, uniqueness: true
end

app/models/trabajando/area.rb
class Trabajando::Area < ActiveRecord::Base
  has_many :publications,
           class: Trabajando::Publication,
           foreign_key: :area_id
  belongs_to :hupe_area, class: Company::Area

  validates :name, presence: true, uniqueness: true
  validates :trabajando_id, presence: true, uniqueness: true
end

app/models/trabajando/career.rb
class Trabajando::Career < ActiveRecord::Base
  belongs_to :hupe_career, class: Education::Career

  validates :name, presence: true
end

app/models/trabajando/city.rb
class Trabajando::City < ActiveRecord::Base
  belongs_to :hupe_city, class_name: Territory::City

  validates :name, presence: true, uniqueness: true
  validates :trabajando_id, presence: true
end

app/models/trabajando/company_activity.rb
class Trabajando::CompanyActivity < ActiveRecord::Base
  has_many :publications, class: Trabajando::Publication
  validates :name, presence: true, uniqueness: true
  validates :trabajando_id, presence: true, uniqueness: true
end

app/models/trabajando/country.rb
class Trabajando::Country < ActiveRecord::Base
  belongs_to :country, class: Territory::Country

  validates :name, presence: true, uniqueness: true
  validates :trabajando_id, presence: true
end

app/models/trabajando/education_level.rb
class Trabajando::EducationLevel < ActiveRecord::Base
  has_many :publications,
           class: Trabajando::Publication

  validates :name, presence: true, uniqueness: true
  validates :trabajando_id, presence: true, uniqueness: true
end

app/controllers/company/marital_statuses_controller.rb
class Company::MaritalStatusesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_action
  before_action :set_company_marital_status, only: [:show, :edit, :update, :destroy]

  # GET /company/marital_statuses
  # GET /company/marital_statuses.json
  def index
    @company_marital_statuses = Company::MaritalStatus.page(params[:page])
  end

  # GET /company/marital_statuses/1
  # GET /company/marital_statuses/1.json
  def show
  end

  # GET /company/marital_statuses/new
  def new
    @company_marital_status = Company::MaritalStatus.new
  end

  # GET /company/marital_statuses/1/edit
  def edit
  end

  # POST /company/marital_statuses
  # POST /company/marital_statuses.json
  def create
    @company_marital_status = Company::MaritalStatus.new(company_marital_status_params)

    respond_to do |format|
      if @company_marital_status.save
        flash[:success] = I18n.t('company/marital_status.actions.create.success')
        format.html { redirect_to @company_marital_status }
        format.json { render :show, status: :created, location: @company_marital_status }
      else
        format.html { render :new }
        format.json { render json: @company_marital_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company/marital_statuses/1
  # PATCH/PUT /company/marital_statuses/1.json
  def update
    respond_to do |format|
      if @company_marital_status.update(company_marital_status_params)
        flash[:success] = I18n.t('company/marital_status.actions.update.success')
        format.html { redirect_to @company_marital_status }
        format.json { render :show, status: :ok, location: @company_marital_status }
      else
        format.html { render :edit }
        format.json { render json: @company_marital_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company/marital_statuses/1
  # DELETE /company/marital_statuses/1.json
  def destroy
    @company_marital_status.destroy
    respond_to do |format|
      flash[:success] = I18n.t('company/marital_status.actions.destroy.success')
      format.html { redirect_to company_marital_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_marital_status
      @company_marital_status = Company::MaritalStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_marital_status_params
      params.require(:company_marital_status).permit(:name)
    end

    def authorize_action
      render 'errors/403', status: 403, layout: 'application' unless current_user.can?(:admin)
    end
end

app/controllers/trabajando/applicant_profiles_controller.rb
class Trabajando::ApplicantProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_action, except: [:show]
  before_action :set_trabajando_applicant_profile, only: [:show, :edit, :update, :destroy]

  # GET /trabajando/applicant_profiles
  # GET /trabajando/applicant_profiles.json
  def index
    @trabajando_applicant_profiles = Trabajando::ApplicantProfile.all.page(params[:page])
  end

  # GET /trabajando/applicant_profiles/1
  # GET /trabajando/applicant_profiles/1.json
  def show
  end

  # GET /trabajando/applicant_profiles/new
  #def new
  #  @trabajando_applicant_profile = Trabajando::ApplicantProfile.new
  #end

  # GET /trabajando/applicant_profiles/1/edit
  def edit
  end

  # POST /trabajando/applicant_profiles
  # POST /trabajando/applicant_profiles.json
  #def create
  #  @trabajando_applicant_profile = Trabajando::ApplicantProfile.new(trabajando_applicant_profile_params)

  #  respond_to do |format|
  #    if @trabajando_applicant_profile.save
  #      format.html { redirect_to @trabajando_applicant_profile, notice: 'Tipo de perfil de candidato creado correctamente.' }
  #      format.json { render :show, status: :created, location: @trabajando_applicant_profile }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @trabajando_applicant_profile.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PATCH/PUT /trabajando/applicant_profiles/1
  # PATCH/PUT /trabajando/applicant_profiles/1.json
  def update
    respond_to do |format|
      if @trabajando_applicant_profile.update(trabajando_applicant_profile_params)
        format.html { redirect_to @trabajando_applicant_profile, notice: 'Actualizado correctamente' }
        format.json { render :show, status: :ok, location: @trabajando_applicant_profile }
      else
        format.html { render :edit }
        format.json { render json: @trabajando_applicant_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /trabajando/applicant_profiles/1
  # # DELETE /trabajando/applicant_profiles/1.json
  # def destroy
  #   @trabajando_applicant_profile.destroy
  #   respond_to do |format|
  #     format.html { redirect_to trabajando_applicant_profiles_url, notice: 'Job type was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajando_applicant_profile
      @trabajando_applicant_profile = Trabajando::ApplicantProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabajando_applicant_profile_params
      params.require(:trabajando_applicant_profile).permit(
        :hupe_profile_type_id
      )
    end

    def authorize_action
      render 'errors/403', status: 403, layout: 'application' unless current_user.can?(:admin)
    end
end

app/views/trabajando/marital_statuses/_form.html.slim
= form_for @trabajando_marital_status do |f|

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control", required: 'required', disabled: true

  .form-group
    = f.label :company_marital_status
    = f.select :company_marital_status_id, Company::MaritalStatus.all.map{ |marital_status| [marital_status[:name], marital_status[:id]] }, {include_blank: true, selected: @trabajando_marital_status.company_marital_status}, class: "form-control js-select"

  .form-group
    .row
      .col-xs-12.col-md-4
        = f.submit class: "btn btn-block btn-success"

app/views/trabajando/marital_statuses/edit.html.slim
- content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = t("resources.generals.labels.editing") + ' ' + Trabajando::MaritalStatus.model_name.human

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'common/info_panel', locals: { main_info: 'trabajando_marital_status' }
          = render partial: 'form'
          .row
            .col-md-2.col-xs-12
              = link_to t("resources.generals.actions.show"), @trabajando_marital_status, class: "btn btn-success btn-block btn-inverted"
            .col-md-2.col-xs-12
              = link_to t("resources.generals.actions.back"), trabajando_marital_statuses_path, class: "btn btn-primary btn-block btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'scaffolds/scaffolds_list'

app/views/trabajando/marital_statuses/index.html.slim
- content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-7.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = Trabajando::MaritalStatus.model_name.human(count: :other)

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'common/info_panel', locals: { main_info: 'trabajando_marital_status' }
          table.table.table-bordered.table-hover
            thead
              tr
                th.small style='vertical-align: middle' = Trabajando::MaritalStatus.human_attribute_name(:name)
                th.small style='vertical-align: middle' = Trabajando::MaritalStatus.human_attribute_name(:company_marital_status)
                th.small

            tbody-body
              - @trabajando_marital_statuses.each do |trabajando_marital_status|
                tr
                  td.small style='vertical-align: middle' width="25%"
                    = link_to trabajando_marital_status.name, trabajando_marital_status, class: "text-base"

                  td.small style='vertical-align: middle' width="70%"
                    - if trabajando_marital_status.company_marital_status_id?
                      = link_to trabajando_marital_status.company_marital_status.name, trabajando_marital_status.company_marital_status
                    - else
                      p Sin estado civil asociado

                  td style='vertical-align: middle' width="42px"
                    = link_to t("resources.generals.actions.edit"), edit_trabajando_marital_status_path(trabajando_marital_status), class: "btn btn-block btn-primary btn-sm"



          = paginate @trabajando_marital_statuses

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/trabajando/marital_statuses/show.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-sm-9.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = @trabajando_marital_status.name

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          label.scaffold_label.__strong = Trabajando::MaritalStatus.human_attribute_name(:name)
          = @trabajando_marital_status.name

          label.scaffold_label.__strong = Trabajando::MaritalStatus.human_attribute_name(:company_marital_status)
          - if @trabajando_marital_status.company_marital_status_id?
             = link_to @trabajando_marital_status.company_marital_status.name, @trabajando_marital_status.company_marital_status
          - else
            p Sin estado civil asociado

        .col-md-2
          = link_to t("resources.generals.actions.edit"), edit_trabajando_marital_status_path(@trabajando_marital_status), class: "btn btn-block btn-primary"

        .col-md-2
          = link_to t("resources.generals.actions.back"), trabajando_marital_statuses_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'scaffolds/scaffolds_list'