config/routes.rb
    get '/me' => 'credentials#me'
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  # Custom Errors
  %w( 404 403 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  # APP
  scope :app do

    get '/', to: 'hupe#index'
    get 'dashboards/general', to: 'dashboards#general'



    resources :scaffolds, only: [:index]

    resources :groups

    namespace :people do
      resources :identification_document_types
    end

    namespace :trabajando do
      resources :careers, only: [:show, :edit, :index, :update]
      resources :universities, only: [:show, :edit, :index, :update]
      resources :job_types, only: [:index,:edit, :update, :show]
      resources :software_levels, only: [:index, :show, :edit, :update]
      resources :education_levels, only: [:index, :show, :edit, :update]
      resources :education_states, only: [:index, :show, :edit, :update]
      resources :applicant_profiles, only: [:show, :edit, :index, :update]
      resources :areas, only: [:index, :show, :edit, :update]
      resources :work_days, only: [:show, :edit, :index, :update]
      resources :company_activities, only: [:show, :edit, :index, :update]
      resources :marital_statuses, only: [:show, :edit, :index, :update]
      resources :countries, only: [:show, :edit, :index, :update]
      resources :states, only: [:show, :edit, :index, :update]
      resources :cities, only: [:show, :edit, :index, :update]
    end

    resources :faqs

    # namespace :minisite do
    #   resources :banners
    # end

    resources :generic_attachments, path: :attachment, only: [:destroy] do
      member do
        get :download
      end
    end

    resources :comment, only: [:index, :create]

    namespace :company do
      resources :areas
      resources :marital_statuses
      resources :vacancy_request_reasons
      resources :records
      resources :contract_types
      resources :positions
      resources :business_units
      resources :cencos
      resources :estates
      resources :recruitment_sources
      resources :timetables
      resources :engagement_origins
      resources :recruitment_sources
      resources :white_ruts do
        collection do
          post :upload_white_list
        end
      end
      resources :employees, only: [:index] do
        collection do
          post :upload_load_massive
          get  :download_file_example
        end
      end
      # resources :references, except: [:destroy, :edit, :update] do
      #   member do
      #     get :confirm
      #   end
      # end
    end


    namespace :video_interview do
      resources :questions
      resources :answers, only: [:show, :index]
    end

    namespace :document do
      resources :descriptors
      resources :groups
      resources :records, only: [:destroy]
    end

    namespace :education do
      resources :study_levels
      resources :institutions do
        collection do
          get :custom
        end

        member do
          put :update_custom
          put :approve_custom
        end
      end

      resources :careers
    end

    namespace :tag do
      resources :course_tags, controller: 'base_tags', type: Tag::CourseTag.to_s
      resources :company_position_tags, controller: 'base_tags', type: Tag::CompanyPositionTag.to_s
    end

    namespace :territory do
      resources :cities
    end

    namespace :territory do
      resources :states
    end

    namespace :territory do
      resources :countries
    end

    namespace :stage do
      resources :not_apply_reasons
    end

    namespace :calendar do
      resources :events, only: [:create, :update] do
        member do
          put :update_for_applicants
          put :mark_attended
          put :mark_will_attend
          get :confirm_will_attend
          get :marked_will_attend
        end

        collection do
          post :create_for_applicants
        end
      end
    end

    namespace :applicant do
      resources :profile_types
      resources :software_levels
      resources :bases, only: [:show, :edit] do
        member do
          put :update
          post :enroll
          post :add_degree
          post :comment
          post :notification_update_profile
          get :generate_cv
          post :upload_documents
          get '/download_document/:name', action: :download_document, as: 'download_document'
          post :update_password
        end
        collection do
          get :index, action: :search
          get :search
          post :_search
          post :enroll
          post :send_update_request
          get :generate_massive_cvs
          post :massive_mailer
        end
      end
      resources :externals, only: [:create, :new]
      resources :catcheds, only: [:create, :new, :edit]
    end

    namespace :worker do
      resources :bases, only: [:create,:new, :show, :edit, :update] do
        member do
          post :add_role
        end
        collection do
          get :index, action: :search
          get :search
        end
      end
    end

    namespace :laborum do
      resources :metadata, only: [], defaults: { format: :json } do
        collection do
          get :areas
          get :subareas
          get :denominaciones
          get :frecuencias_pago
          get :denominaciones
          get :direcciones
          get :idiomas
          get :niveles_idiomas
          get :industrias
          get :tipos_trabajo
          get :areas_estudio
          get :estados_estudio
          get :tipos_estudio
          get :paises
          get :regiones
          get :comunas
        end
      end
    end

    namespace :enrollment do
      resources :bases, only: [] do
        member do
          post :discard

          get :mark_invitation_accepted
          get :mark_invitation_rejected

          resources :offer_letters, only: [], param: :offer_letter_id  do
            member do
              get :accept
              get :show_reject
              post :reject
              get :answered
            end
          end
        end

        collection do
          post :invite
          post :dispose
          post :revert_dispose
          post :next_stage
          get :export
          post :unenroll
        end
      end

      resources :discard_reasons do
        member do
          post :set_as_default_when_close_course
          post :toggle_blacklist
        end
      end
    end

    namespace :hiring_request do
      resources :records, except: [:destroy] do
        member do
          put :switch_state
        end
        collection do
          post :_search
        end
      end
    end

    resources :vacancies, only: [] do
      collection do
        put :assign_course
        put :assign_new_course
      end
    end

    namespace :offer do
      resources :letters, only: [] do
        member do
          post :accept
        end
      end
      resources :reject_reasons
    end

    resources :courses, only: [:create, :new, :show, :edit, :update] do
      member do
        resources :course_postulations, only: [:index] do
          collection do
            post :_search
            post :accept
            post :reject
            post :reset
            get :export
          end
        end

        post :_search, action: :_search_candidates

        # Modulo de VideoInterview
        namespace :video_interview, as: :course_video_interview do
          resources :stages, only: [:show], param: :stage_id do
          end
        end
        # Modulo de Promotion
        namespace :promotion, as: :course_promotion do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              post :send_acceptance_email
            end
          end
        end

        # Módulo stage (genérico)
        namespace :stage, as: :course_stage do
          resources :bases, only: [], param: :stage_id do
          end
        end

        # Modulo de manager_interview
        namespace :manager_interview, as: :course_manager_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de skill_interview
        namespace :skill_interview, as: :course_skill_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de assigning_weighting
        namespace :assigning_weighting, as: :course_assigning_weighting do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de internal_postulation
        namespace :internal_postulation, as: :course_internal_postulation do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :records, only: [:create], param: :record_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de test
        namespace :test, as: :course_test do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end

app/models/territory.rb
module Territory
  def self.table_name_prefix
    'territory_'
  end
end

app/controllers/territory/cities_controller.rb
class Territory::CitiesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_action, except: [:show, :index]
  before_action :set_territory_city, only: [:show, :edit, :update, :destroy]

  # GET /territory/cities
  # GET /territory/cities.json
  def index
    respond_to do |format|
      format.html { @territory_cities = Territory::City.page(params[:page]) }
      format.json { @territory_cities = Territory::City.all }
    end
  end

  # GET /territory/cities/1
  # GET /territory/cities/1.json
  def show
  end

  # GET /territory/cities/new
  def new
    @territory_city = Territory::City.new
  end

  # GET /territory/cities/1/edit
  def edit
  end

  # POST /territory/cities
  # POST /territory/cities.json
  def create
    @territory_city = Territory::City.new(territory_city_params)

    respond_to do |format|
      if @territory_city.save
        flash[:success] = t("resources.territory.cities.create_success")
        format.html { redirect_to @territory_city }
        format.json { render :show, status: :created, location: @territory_city }
      else
        flash.now[:error] = @territory_city.errors.messages
        format.html { render :new }
        format.json { render json: @territory_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /territory/cities/1
  # PATCH/PUT /territory/cities/1.json
  def update
    respond_to do |format|
      if @territory_city.update(territory_city_params)
        flash[:success] = t("resources.territory.cities.update_success")
        format.html { redirect_to @territory_city }
        format.json { render :show, status: :ok, location: @territory_city }
      else
        flash.now[:error] = @territory_city.errors.messages
        format.html { render :edit }
        format.json { render json: @territory_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /territory/cities/1
  # DELETE /territory/cities/1.json
  def destroy
    @territory_city.destroy
    respond_to do |format|
      flash[:success] = t("resources.territory.cities.destroy_success")
      format.html { redirect_to territory_cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_territory_city
      @territory_city = Territory::City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def territory_city_params
      begin
        territory_state = Territory::State.find(params[:territory_city][:territory_state])
      rescue Exception => e
        territory_state = nil
      end
      params.require(:territory_city).permit(:name).merge(territory_state: territory_state)
    end

    def authorize_action
      render 'errors/403', :status => 403, layout: 'application' unless current_user.can?(:admin)
    end
end

app/controllers/territory/countries_controller.rb
class Territory::CountriesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_action, except: [:show, :index]
  before_action :set_territory_country, only: [:show, :edit, :update, :destroy]

  # GET /territory/countries
  # GET /territory/countries.json
  def index
    respond_to do |format|
      format.html { @territory_countries = Territory::Country.page(params[:page]) }
      format.json { @territory_countries = Territory::Country.all }
    end
  end

  # GET /territory/countries/1
  # GET /territory/countries/1.json
  def show
  end

  # GET /territory/countries/new
  def new
    @territory_country = Territory::Country.new
  end

  # GET /territory/countries/1/edit
  def edit
  end

  # POST /territory/countries
  # POST /territory/countries.json
  def create
    @territory_country = Territory::Country.new(territory_country_params)

    respond_to do |format|
      if @territory_country.save
        flash[:success] = t("resources.territory.countries.create_success")
        format.html { redirect_to @territory_country }
        format.json { render :show, status: :created, location: @territory_country }
      else
        flash.now[:error] = @territory_country.errors.messages
        format.html { render :new }
        format.json { render json: @territory_country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /territory/countries/1
  # PATCH/PUT /territory/countries/1.json
  def update
    respond_to do |format|
      if @territory_country.update(territory_country_params)
        flash[:success] = t("resources.territory.countries.update_success")
        format.html { redirect_to @territory_country }
        format.json { render :show, status: :ok, location: @territory_country }
      else
        flash.now[:error] = @territory_country.errors.messages
        format.html { render :edit }
        format.json { render json: @territory_country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /territory/countries/1
  # DELETE /territory/countries/1.json
  def destroy
    @territory_country.destroy
    respond_to do |format|
      flash[:success] = t("resources.territory.countries.destroy_success")
      format.html { redirect_to territory_countries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_territory_country
      @territory_country = Territory::Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def territory_country_params
      params.require(:territory_country).permit(:name)
    end

    def authorize_action
      render 'errors/403', :status => 403, layout: 'application' unless current_user.can?(:admin)
    end
end

app/controllers/trabajando/countries_controller.rb
class Trabajando::CountriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_action
  before_action :set_trabajando_country, only: [:show, :edit, :update]

  # GET /trabajando/countries
  # GET /trabajando/countries.json
  def index
    @trabajando_countries = Trabajando::Country.all.page(params[:page])
  end

  # GET /trabajando/countries/1
  # GET /trabajando/countries/1.json
  def show
  end


  # GET /trabajando/countries/1/edit
  def edit
  end

  # PATCH/PUT /trabajando/countries/1
  # PATCH/PUT /trabajando/countries/1.json
  def update
    respond_to do |format|
      if @trabajando_country.update(trabajando_country_params)
        format.html { redirect_to @trabajando_country, notice: 'Actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @trabajando_country }
      else
        format.html { render :edit }
        format.json { render json: @trabajando_country.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajando_country
      @trabajando_country = Trabajando::Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabajando_country_params
      params.require(:trabajando_country).permit(:name, :trabajando_id, :country_id)
    end

    def authorize_action
      render 'errors/403', status: 403, layout: 'application' unless current_user.can?(:admin)
    end
end

app/helpers/territory/cities_helper.rb
module Territory::CitiesHelper
end

app/helpers/territory/countries_helper.rb
module Territory::CountriesHelper
end

app/helpers/territory/states_helper.rb
module Territory::StatesHelper
end

app/views/territory/countries/_form.html.slim
= form_for(@territory_country) do |f| 

  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control", autofocus: true, required: field_required?(f, :name)

  .form-group
    .row
      .col-xs-12.col-md-3
        = f.submit class: "btn btn-block btn-success"

app/views/territory/countries/edit.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = t("resources.generals.labels.editing") + ' ' + t("resources.territory.countries.singular")

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'common/info_panel', locals: { main_info: 'territory' }
          = render partial: 'form'
          .row
            .col-xs-12.col-md-3.padding-bottom-10-px
              = link_to t("resources.generals.actions.back"), territory_countries_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/territory/countries/index.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-sm-9.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = t("resources.territory.countries.title")
        .col-xs-6.col-sm-3.col-md-2
          .margin-top-10-px
            .col-xs-12
              = link_to t("resources.generals.labels.new.m") + ' ' + t("resources.territory.countries.singular"), new_territory_country_path, class: "btn btn-block btn-success"

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'common/info_panel', locals: { main_info: 'territory' }
          table.table.table-bordered.table-hover
            thead
              tr
                th.small style='vertical-align: middle' = t("resources.generals.labels.name")
                th.small style='vertical-align: middle' colspan='3'

            tbody
              - @territory_countries.each do |territory_country|
                tr
                  td.small style='vertical-align: middle' width="84%"
                    = link_to territory_country.name, territory_country , class: "text-base"

                  td.small style='vertical-align: middle'
                    = link_to t("resources.generals.actions.edit"), edit_territory_country_path(territory_country), class: "btn btn-block btn-primary btn-sm"

                  td.small style='vertical-align: middle'
                    = link_to t("resources.generals.actions.destroy"), territory_country, method: :delete, data: { confirm: (t("resources.generals.actions.destroy_confirm") + ' ' + territory_country.name + ' ?') }, class: "btn btn-block btn-danger btn-sm"

          = paginate @territory_countries

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/territory/countries/new.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = t("resources.generals.labels.new.m") + ' ' + t("resources.territory.countries.singular")
.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'form'

          .row
            .col-xs-12.col-md-3.padding-bottom-10-px
              = link_to t("resources.generals.actions.back"), territory_countries_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/territory/countries/show.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = @territory_country.name.capitalize

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          label = t("resources.generals.labels.name")
          p = @territory_country.name

          .row
            .col-xs-12.col-md-3.padding-bottom-10-px
              = link_to t("resources.generals.actions.edit"), edit_territory_country_path(@territory_country), class: "btn btn-block btn-primary"
            .col-xs-12.col-md-3.padding-bottom-10-px
              = link_to t("resources.generals.actions.back"), territory_countries_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"