config/routes.rb
    get code, :to => "errors#show", :code => code
  end

  # APP
  scope :app do

    get '/', to: 'hupe#index'
    get 'dashboards/general', to: 'dashboards#general'



    resources :scaffolds, only: [:index]

    resources :groups

    namespace :people do
      resources :identification_document_types
    end

    namespace :trabajando do
      resources :careers, only: [:show, :edit, :index, :update]
      resources :universities, only: [:show, :edit, :index, :update]
      resources :job_types, only: [:index,:edit, :update, :show]
      resources :software_levels, only: [:index, :show, :edit, :update]
      resources :education_levels, only: [:index, :show, :edit, :update]
      resources :education_states, only: [:index, :show, :edit, :update]
      resources :applicant_profiles, only: [:show, :edit, :index, :update]
      resources :areas, only: [:index, :show, :edit, :update]
      resources :work_days, only: [:show, :edit, :index, :update]
      resources :company_activities, only: [:show, :edit, :index, :update]
      resources :marital_statuses, only: [:show, :edit, :index, :update]
      resources :countries, only: [:show, :edit, :index, :update]
      resources :states, only: [:show, :edit, :index, :update]
      resources :cities, only: [:show, :edit, :index, :update]
    end

    resources :faqs

    # namespace :minisite do
    #   resources :banners
    # end

    resources :generic_attachments, path: :attachment, only: [:destroy] do
      member do
        get :download
      end
    end

    resources :comment, only: [:index, :create]

    namespace :company do
      resources :areas
      resources :marital_statuses
      resources :vacancy_request_reasons
      resources :records
      resources :contract_types
      resources :positions
      resources :business_units
      resources :cencos
      resources :estates
      resources :recruitment_sources
      resources :timetables
      resources :engagement_origins
      resources :recruitment_sources
      resources :white_ruts do
        collection do
          post :upload_white_list
        end
      end
      resources :employees, only: [:index] do
        collection do
          post :upload_load_massive
          get  :download_file_example
        end
      end
      # resources :references, except: [:destroy, :edit, :update] do
      #   member do
      #     get :confirm
      #   end
      # end
    end


    namespace :video_interview do
      resources :questions
      resources :answers, only: [:show, :index]
    end

    namespace :document do
      resources :descriptors
      resources :groups
      resources :records, only: [:destroy]
    end

    namespace :education do
      resources :study_levels
      resources :institutions do
        collection do
          get :custom
        end

        member do
          put :update_custom
          put :approve_custom
        end
      end

      resources :careers
    end

    namespace :tag do
      resources :course_tags, controller: 'base_tags', type: Tag::CourseTag.to_s
      resources :company_position_tags, controller: 'base_tags', type: Tag::CompanyPositionTag.to_s
    end

    namespace :territory do
      resources :cities
    end

    namespace :territory do
      resources :states
    end

    namespace :territory do
      resources :countries
    end

    namespace :stage do
      resources :not_apply_reasons
    end

    namespace :calendar do
      resources :events, only: [:create, :update] do
        member do
          put :update_for_applicants
          put :mark_attended
          put :mark_will_attend
          get :confirm_will_attend
          get :marked_will_attend
        end

        collection do
          post :create_for_applicants
        end
      end
    end

    namespace :applicant do
      resources :profile_types
      resources :software_levels
      resources :bases, only: [:show, :edit] do
        member do
          put :update
          post :enroll
          post :add_degree
          post :comment
          post :notification_update_profile
          get :generate_cv
          post :upload_documents
          get '/download_document/:name', action: :download_document, as: 'download_document'
          post :update_password
        end
        collection do
          get :index, action: :search
          get :search
          post :_search
          post :enroll
          post :send_update_request
          get :generate_massive_cvs
          post :massive_mailer
        end
      end
      resources :externals, only: [:create, :new]
      resources :catcheds, only: [:create, :new, :edit]
    end

    namespace :worker do
      resources :bases, only: [:create,:new, :show, :edit, :update] do
        member do
          post :add_role
        end
        collection do
          get :index, action: :search
          get :search
        end
      end
    end

    namespace :laborum do
      resources :metadata, only: [], defaults: { format: :json } do
        collection do
          get :areas
          get :subareas
          get :denominaciones
          get :frecuencias_pago
          get :denominaciones
          get :direcciones
          get :idiomas
          get :niveles_idiomas
          get :industrias
          get :tipos_trabajo
          get :areas_estudio
          get :estados_estudio
          get :tipos_estudio
          get :paises
          get :regiones
          get :comunas
        end
      end
    end

    namespace :enrollment do
      resources :bases, only: [] do
        member do
          post :discard

          get :mark_invitation_accepted
          get :mark_invitation_rejected

          resources :offer_letters, only: [], param: :offer_letter_id  do
            member do
              get :accept
              get :show_reject
              post :reject
              get :answered
            end
          end
        end

        collection do
          post :invite
          post :dispose
          post :revert_dispose
          post :next_stage
          get :export
          post :unenroll
        end
      end

      resources :discard_reasons do
        member do
          post :set_as_default_when_close_course
          post :toggle_blacklist
        end
      end
    end

    namespace :hiring_request do
      resources :records, except: [:destroy] do
        member do
          put :switch_state
        end
        collection do
          post :_search
        end
      end
    end

    resources :vacancies, only: [] do
      collection do
        put :assign_course
        put :assign_new_course
      end
    end

    namespace :offer do
      resources :letters, only: [] do
        member do
          post :accept
        end
      end
      resources :reject_reasons
    end

    resources :courses, only: [:create, :new, :show, :edit, :update] do
      member do
        resources :course_postulations, only: [:index] do
          collection do
            post :_search
            post :accept
            post :reject
            post :reset
            get :export
          end
        end

        post :_search, action: :_search_candidates

        # Modulo de VideoInterview
        namespace :video_interview, as: :course_video_interview do
          resources :stages, only: [:show], param: :stage_id do
          end
        end
        # Modulo de Promotion
        namespace :promotion, as: :course_promotion do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              post :send_acceptance_email
            end
          end
        end

        # Módulo stage (genérico)
        namespace :stage, as: :course_stage do
          resources :bases, only: [], param: :stage_id do
          end
        end

        # Modulo de manager_interview
        namespace :manager_interview, as: :course_manager_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de skill_interview
        namespace :skill_interview, as: :course_skill_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de assigning_weighting
        namespace :assigning_weighting, as: :course_assigning_weighting do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de internal_postulation
        namespace :internal_postulation, as: :course_internal_postulation do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :records, only: [:create], param: :record_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de test
        namespace :test, as: :course_test do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de offer
        namespace :offer, as: :course_offer do
          resources :stages, only: [:show], param: :stage_id do

app/models/assigning_weighting/stage.rb
class AssigningWeighting::Stage <  Stage::Base
  has_one :assigning_weighting_report,
          class_name: AssigningWeighting::Report,
          foreign_key: :assigning_weighting_stage_id,
          dependent: :destroy

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("assigning_weighting.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("assigning_weighting.stage.roles.instance.admin")},
    ]
  end
end

app/models/engagement/stage.rb
# == Schema Information
#
# Table name: stage_bases
#
#  id            :integer          not null, primary key
#  enrollment_id :integer
#  type          :string
#  created_at    :datetime
#  updated_at    :datetime
#  step          :integer
#  name          :string
#

class Engagement::Stage <  Stage::Base
  validates :type, uniqueness: { scope: [:enrollment_id]}

  has_one :agreement, class_name: Engagement::Agreement, foreign_key: :engagement_stage_id, dependent: :destroy

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("engagement.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("engagement.stage.roles.instance.admin")},
    ]
  end

  def disposable?
    if self.agreement.nil?
      return true
    else
      error = I18n.t('activerecord.errors.models.engagement/stage.attributes.enrollment.undisposable')
      self.enrollment.errors.add(:discarding, error)
      return false
    end
  end

  def is_hired?
    self.agreement.present?
  end

  def can_not_apply?
    return false if is_hired?
    super
  end

  def is_approved?
    agreement.present? ? true : nil
  end
end

app/models/final_interview/stage.rb
class FinalInterview::Stage <  Stage::Base
  has_one :final_interview_report,
          class_name: FinalInterview::Report,
          foreign_key: :final_interview_stage_id,
          dependent: :destroy

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("final_interview.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("final_interview.stage.roles.instance.admin")},
    ]
  end

  def can_not_apply?
    return false if self.final_interview_report.present?
    super
  end

end

app/models/group_interview/stage.rb
class GroupInterview::Stage <  Stage::Base
  has_one :group_interview_report,
          class_name: GroupInterview::Report,
          foreign_key: :group_interview_stage_id,
          dependent: :destroy

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("group_interview.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("group_interview.stage.roles.instance.admin")},
    ]
  end

  def can_not_apply?
    return false if self.group_interview_report.present?
    super
  end

end

app/models/interview/stage.rb
# == Schema Information
#
# Table name: stage_bases
#
#  id            :integer          not null, primary key
#  enrollment_id :integer
#  type          :string
#  created_at    :datetime
#  updated_at    :datetime
#  step          :integer
#  name          :string
#

class Interview::Stage <  Stage::Base
  has_one :interview_report,
          class_name: Interview::Report,
          foreign_key: :interview_stage_id,
          dependent: :destroy

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("interview.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("interview.stage.roles.instance.admin")},
    ]
  end

  def to_s
    'Entrevista'
  end

end

app/models/manager_interview/stage.rb
class ManagerInterview::Stage <  Stage::Base
  has_one :manager_interview_report,
          class_name: ManagerInterview::Report,
          foreign_key: :manager_interview_stage_id,
          dependent: :destroy

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("manager_interview.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("manager_interview.stage.roles.instance.admin")},
    ]
  end

  def can_not_apply?
    return false if self.manager_interview_report.present?
    super
  end
end

app/models/offer/stage.rb
# == Schema Information
#
# Table name: stage_bases
#
#  id            :integer          not null, primary key
#  enrollment_id :integer
#  type          :string
#  created_at    :datetime
#  updated_at    :datetime
#  step          :integer
#  name          :string
#

class Offer::Stage <  Stage::Base
  has_one :offer_letter, class_name: Offer::Letter, dependent: :destroy

  validates :type, uniqueness: { scope: [:enrollment_id]}

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("offer.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("offer.stage.roles.instance.admin")},
    ]
  end

  def can_not_apply?
    offer_letter = Offer::Letter.find_by(stage: self)
    return false if offer_letter.present?
    super
  end

  def is_approved?
    offer_letter.present? ? offer_letter.accepted : nil
  end
end

app/models/onboarding.rb
module Onboarding
  def self.table_name_prefix
    'onboarding_'
  end

  def self.to_s
    "Documentación"
  end
end

app/models/onboarding/document_group.rb
class Onboarding::DocumentGroup < ActiveRecord::Base
  belongs_to :onboarding_stage,
             class_name: Onboarding::Stage,
             foreign_key: :onboarding_stage_id

  belongs_to :document_group,
             class_name: Document::Group,
             foreign_key: :document_group_id

  validates :document_group, presence: true
  validates :onboarding_stage, presence: true
end

app/models/onboarding/stage.rb
# == Schema Information
#
# Table name: stage_bases
#
#  id            :integer          not null, primary key
#  enrollment_id :integer
#  type          :string
#  created_at    :datetime
#  updated_at    :datetime
#  step          :integer
#  name          :string
#

class Onboarding::Stage < Stage::Base
  after_create :create_onboarding_document_group
  after_create :send_upload_requested_documents_email
  validates :type, uniqueness: { scope: [:enrollment_id]}

  has_one :onboarding_document_group,
          class_name: Onboarding::DocumentGroup,
          foreign_key: :onboarding_stage_id,
          dependent: :destroy


  delegate :document_group, to: :onboarding_document_group, allow_nil: true

  ROLES_CLASS = [
    {name: :admin, description: I18n.t("onboarding.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("onboarding.stage.roles.instance.admin")}
    ]
  end

  def send_upload_requested_documents_email
    offer_letter = self.enrollment.stages.find_by(type: Offer::Stage).try(:offer_letter)

    if  offer_letter && offer_letter.accepted
      Onboarding::StageMailer.delay.send_upload_documentation_request(self)
    end
  end

  private
    def create_onboarding_document_group
      Onboarding::DocumentGroup.create(onboarding_stage: self, document_group_id: (self.args.try(:[], :document_group) || self.enrollment.course.document_group.id))
    end

end

app/models/promotion/stage.rb
  # coding: utf-8
class Promotion::Stage <  Stage::Base
  ROLES_CLASS = [
    {name: :admin, description: I18n.t("promotion.stage.roles.class.admin")}
  ]

  def roles_instance
    [
      {name: :admin, description: I18n.t("promotion.stage.roles.instance.admin")},
    ]
  end

  def send_acceptance_email
    close_vacancy
    Promotion::StageMailer.delay.send_acceptance_email(self)
  end

  def to_s
    return "Promoción"
  end

  private

  def close_vacancy
    self.enrollment.course.vacancies.last.update(closed_at: self.created_at)
  end
end

app/models/stage.rb
module Stage
  def self.table_name_prefix
    'stage_'
  end

  def self.to_s
    "Etapa"
  end
end

app/views/onboarding/stages/_form.html.slim
.row.margin-top-10-px

    section.course_card
      .row.course_card-title.__large
        .col-sm-5
          .row
            h4
              = Onboarding::Stage.model_name.human

      .row
        .col-md-12
          p
            - if @stage.document_group
              b
                = t("resources.document.group.request") + ': '
                = @stage.document_group.name
          br/

          - if support_react_document_uploader?
            ul#document-list.document-upload-list.accordion aria-multiselectable="true"
              - applicant = @stage.enrollment.applicant
              - @document_descriptors = @stage.document_group.document_descriptors
              - @document_records = @applicant.document_records.order('created_at ASC')

              = react_component "DocumentWrapperAction", {\
                applicant_id: applicant.id, \
                document_descriptors: JSON.parse(render(template: 'document/descriptors/index.json.jbuilder')), \
                document_records: JSON.parse(render(template: 'document/records/index.json.jbuilder')), \
                upload_path: do_upload_document_course_onboarding_stage_path(@course.id, @stage.id), \
                request_path: documents_request_course_onboarding_stage_path(@course.id, @stage.id),\
                show_document_request: true, \
                show_origin: true, \
                is_admin: current_user.can?(:admin) \
              }
          - else
            = form_for([@stage.enrollment.course, @stage], url: do_upload_document_course_onboarding_stage_path, method: 'POST', as: 'applicant_documents') do |f|
              .row
                div.col-md-6.col-md-offset-6.margin-bottom-10-px
                  = f.submit (t("actions.upload") + ' ' + Document::Record.human_attribute_name(:documents)), class: "btn btn-primary pull-right"

              - @stage.document_group.document_descriptors.each do |desc|
                .well.well-sm
                  .create-course_row.clearfix
                    .form-group
                      = f.label desc.details, desc.details
                      = f.file_field desc.to_sym

                  .row
                    .col-md-12
                      .col-md-12
                        - if @stage.enrollment.applicant.has_document(desc.name)
                          .btn-group aria-label="..." role="group"
                            = link_to t("actions.download"), download_document_course_onboarding_stage_path(@stage.enrollment.course, @stage, desc.name), class: "btn btn-success"

                          - records = @stage.enrollment.applicant.document_records.where(document_descriptor: desc).order("id desc")
                          - current_record =  @applicant.get_latest_document_record(desc.name, @stage.enrollment.id)
                          br/
                          a class="btn btn-default btn-xs margin-top-15-px" role="button" data-toggle="collapse" href="#allDocuments-#{desc.name}" aria-expanded="false" aria-controls="allDocuments-#{desc.name}"
                            = "Mostrar todas las versiones"
                          div class="collapse" id="allDocuments-#{desc.name}"
                            table class="table table-hover"
                              thead
                                tr
                                  th
                                    = t('onboarding.date')
                                  th
                                    = t('onboarding.origin')
                              tbody
                                - records.each do |record|
                                  - if record.id == current_record.id
                                    - tr_class = 'success'
                                  - else
                                    - tr_class = ''
                                  tr class="active #{tr_class}"
                                    td
                                      = link_to l(record.created_at, format: :long).capitalize, download_document_course_onboarding_stage_path(@stage.enrollment.course, @stage, desc.name, record_id: record.id)
                                    td
                                      - if record.enrollment.present?
                                        = "#{t('activerecord.models.course.one')}: "
                                        = link_to record.enrollment.course.title, course_path(record.enrollment.course)
                                      - else
                                        = link_to t('profiles.myprofile'), applicant_basis_path(@applicant)

app/views/onboarding/stages/show.html.slim
- content_for :subheader do
  = render partial: "courses/subheader", locals: {candidates: '__active'}


= render partial: 'onboarding/stages/form'

app/views/onboarding/stages/upload_requested_documents.html.slim
= flash_box_printer
- document_descriptors = @stage.document_group.document_descriptors.where(internal: [nil, false])
- document_descriptors = document_descriptors.where(id: params[:document_descriptor]) if params[:document_descriptor].present?
- if support_react_document_uploader?
  ul#document-list.document-upload-list.accordion aria-multiselectable="true"
    - document_descriptors.each do |descriptor|
      - applicant = @applicant
      - @document_descriptor = descriptor
      - @document_records = @applicant.document_records.where(document_descriptor: descriptor).order('created_at ASC')
      = react_component 'DocumentWrapper', { \
          applicant_id: applicant.id, \
          auth_token: form_authenticity_token, \
          document_descriptor: JSON.parse(render(template: 'document/descriptors/show.json.jbuilder')), \
          document_records: JSON.parse(render(template: 'document/records/index.json.jbuilder')), \
          upload_path: do_upload_requested_documents_course_onboarding_stage_path(token: @token), \
          show_origin: false \
        }, { tag: 'li', class: 'document-item-wrapper clearfix' }


- else
  - current_user = @applicant.user
  = form_for([current_user], url: do_upload_requested_documents_course_onboarding_stage_path(token: @token), method: 'POST', as: 'applicant_documents') do |f|
          .panel.panel-default.margin-top-10-px
            .panel-heading.clearfix
              .col-sm-11
                h3.margin-top-10-px
                  = t('documents.title')
              .col-sm-1
                = f.submit 'Subir archivos', class: "btn btn-success btn-block margin-top-10-px"

            .panel-body
              - document_descriptors.each do |desc|
                ul
                  li
                    = f.label desc.details, desc.details, class: "create-course_label"
                    =  f.file_field desc.to_sym
                    /= link_to 'Descargar', download_document_profiles_path(desc.name) if current_user.has_document(desc.name)