config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  namespace :minisite do
    resources :banners
  end

  # omniauth with doorkeeper
  use_doorkeeper do
    skip_controllers :applications
  end

  namespace :auth do
    get '/me' => 'credentials#me'
  end

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  # Custom Errors
  %w( 404 403 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  # APP
  scope :app do

    get '/', to: 'hupe#index'
    get 'dashboards/general', to: 'dashboards#general'



    resources :scaffolds, only: [:index]

    resources :groups

    namespace :people do
      resources :identification_document_types
    end

    namespace :trabajando do
      resources :careers, only: [:show, :edit, :index, :update]
      resources :universities, only: [:show, :edit, :index, :update]
      resources :job_types, only: [:index,:edit, :update, :show]
      resources :software_levels, only: [:index, :show, :edit, :update]
      resources :education_levels, only: [:index, :show, :edit, :update]
      resources :education_states, only: [:index, :show, :edit, :update]
      resources :applicant_profiles, only: [:show, :edit, :index, :update]
      resources :areas, only: [:index, :show, :edit, :update]
      resources :work_days, only: [:show, :edit, :index, :update]
      resources :company_activities, only: [:show, :edit, :index, :update]
      resources :marital_statuses, only: [:show, :edit, :index, :update]
      resources :countries, only: [:show, :edit, :index, :update]
      resources :states, only: [:show, :edit, :index, :update]
      resources :cities, only: [:show, :edit, :index, :update]
    end

    resources :faqs

    # namespace :minisite do
    #   resources :banners
    # end

    resources :generic_attachments, path: :attachment, only: [:destroy] do
      member do
        get :download
      end
    end

    resources :comment, only: [:index, :create]

    namespace :company do
      resources :areas
      resources :marital_statuses
      resources :vacancy_request_reasons
      resources :records
      resources :contract_types
      resources :positions
      resources :business_units
      resources :cencos
      resources :estates
      resources :recruitment_sources
      resources :timetables
      resources :engagement_origins
      resources :recruitment_sources
      resources :white_ruts do
        collection do
          post :upload_white_list
        end
      end
      resources :employees, only: [:index] do
        collection do
          post :upload_load_massive
          get  :download_file_example
        end
      end
      # resources :references, except: [:destroy, :edit, :update] do
      #   member do
      #     get :confirm
      #   end
      # end
    end


    namespace :video_interview do
      resources :questions
      resources :answers, only: [:show, :index]
    end

    namespace :document do
      resources :descriptors
      resources :groups
      resources :records, only: [:destroy]
    end

    namespace :education do
      resources :study_levels
      resources :institutions do
        collection do
          get :custom
        end

        member do
          put :update_custom
          put :approve_custom
        end
      end

      resources :careers
    end

    namespace :tag do
      resources :course_tags, controller: 'base_tags', type: Tag::CourseTag.to_s
      resources :company_position_tags, controller: 'base_tags', type: Tag::CompanyPositionTag.to_s
    end

    namespace :territory do
      resources :cities
    end

    namespace :territory do
      resources :states
    end

    namespace :territory do
      resources :countries
    end

    namespace :stage do
      resources :not_apply_reasons
    end

    namespace :calendar do
      resources :events, only: [:create, :update] do
        member do
          put :update_for_applicants
          put :mark_attended
          put :mark_will_attend
          get :confirm_will_attend
          get :marked_will_attend
        end

        collection do
          post :create_for_applicants
        end
      end
    end

    namespace :applicant do
      resources :profile_types
      resources :software_levels
      resources :bases, only: [:show, :edit] do
        member do
          put :update
          post :enroll
          post :add_degree
          post :comment
          post :notification_update_profile
          get :generate_cv
          post :upload_documents
          get '/download_document/:name', action: :download_document, as: 'download_document'
          post :update_password
        end
        collection do
          get :index, action: :search
          get :search
          post :_search
          post :enroll
          post :send_update_request
          get :generate_massive_cvs
          post :massive_mailer
        end
      end
      resources :externals, only: [:create, :new]
      resources :catcheds, only: [:create, :new, :edit]
    end

    namespace :worker do
      resources :bases, only: [:create,:new, :show, :edit, :update] do
        member do
          post :add_role
        end
        collection do
          get :index, action: :search
          get :search
        end
      end
    end

    namespace :laborum do
      resources :metadata, only: [], defaults: { format: :json } do
        collection do
          get :areas
          get :subareas
          get :denominaciones
          get :frecuencias_pago
          get :denominaciones
          get :direcciones
          get :idiomas
          get :niveles_idiomas
          get :industrias
          get :tipos_trabajo
          get :areas_estudio
          get :estados_estudio
          get :tipos_estudio
          get :paises
          get :regiones
          get :comunas
        end
      end
    end

    namespace :enrollment do
      resources :bases, only: [] do
        member do
          post :discard

          get :mark_invitation_accepted
          get :mark_invitation_rejected

          resources :offer_letters, only: [], param: :offer_letter_id  do
            member do
              get :accept
              get :show_reject
              post :reject
              get :answered
            end
          end
        end

        collection do
          post :invite
          post :dispose
          post :revert_dispose
          post :next_stage
          get :export
          post :unenroll
        end
      end

      resources :discard_reasons do
        member do
          post :set_as_default_when_close_course
          post :toggle_blacklist
        end
      end
    end

    namespace :hiring_request do
      resources :records, except: [:destroy] do
        member do
          put :switch_state
        end
        collection do
          post :_search
        end
      end
    end

    resources :vacancies, only: [] do
      collection do
        put :assign_course
        put :assign_new_course
      end
    end

    namespace :offer do
      resources :letters, only: [] do
        member do
          post :accept
        end
      end
      resources :reject_reasons
    end

    resources :courses, only: [:create, :new, :show, :edit, :update] do
      member do
        resources :course_postulations, only: [:index] do
          collection do
            post :_search
            post :accept
            post :reject
            post :reset
            get :export
          end
        end

        post :_search, action: :_search_candidates

        # Modulo de VideoInterview
        namespace :video_interview, as: :course_video_interview do
          resources :stages, only: [:show], param: :stage_id do
          end
        end
        # Modulo de Promotion
        namespace :promotion, as: :course_promotion do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              post :send_acceptance_email
            end
          end
        end

        # Módulo stage (genérico)
        namespace :stage, as: :course_stage do
          resources :bases, only: [], param: :stage_id do
          end
        end

        # Modulo de manager_interview
        namespace :manager_interview, as: :course_manager_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de skill_interview
        namespace :skill_interview, as: :course_skill_interview do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de assigning_weighting
        namespace :assigning_weighting, as: :course_assigning_weighting do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :reports, only: [:create], param: :report_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de internal_postulation
        namespace :internal_postulation, as: :course_internal_postulation do
          resources :stages, only: [:show, :index], param: :stage_id do
            member do
              resources :records, only: [:create], param: :record_id do
                member do
                  get :download
                end
              end
            end
          end
        end

        # Modulo de test
        namespace :test, as: :course_test do
          resources :stages, only: [:show, :index], param: :stage_id do

app/models/minisite/question.rb
# == Schema Information
#
# Table name: minisite_questions
#
#  id                      :integer          not null, primary key
#  minisite_publication_id :integer
#  description             :text
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Minisite::Question < ActiveRecord::Base
  belongs_to :minisite_publication,
             class_name: Minisite::Publication,
             inverse_of: :questions

  has_many :answers,
           class_name: Minisite::Answer,
           foreign_key: :minisite_question_id,
           inverse_of: :minisite_question

  validates :minisite_publication, presence: true
  validates :description, presence: true, uniqueness: { scope: [:minisite_publication_id] }
end

app/models/video_interview/answer.rb
# == Schema Information
#
# Table name: video_interview_answers
#
#  id            :integer          not null, primary key
#  time_limit    :integer
#  question      :string
#  enrollment_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

class VideoInterview::Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :enrollment, class_name: Enrollment::Base
  #f4_cameraized
end

app/models/video_interview/question.rb
# == Schema Information
#
# Table name: video_interview_questions
#
#  id         :integer          not null, primary key
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class VideoInterview::Question < ActiveRecord::Base
  validates :content, presence: true
  has_and_belongs_to_many :courses
end

app/controllers/video_interview/answers_controller.rb
class VideoInterview::AnswersController < ApplicationController
  before_action :set_video_interview_answer, only: [:show]
  acts_as_token_authentication_handler_for User

  # GET /video_interview/answers
  # GET /video_interview/answers.json
  def index
    @video_interview_answers = VideoInterview::Answer.all
  end

  # GET /video_interview/answers/1
  # GET /video_interview/answers/1.json
  def show
    if @video_interview_answer.video_state == :uploaded
      redirect_to :root, notice: 'Esta pregunta ya fue respondida.'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_interview_answer
      @video_interview_answer = VideoInterview::Answer.find(params[:id])
    end
end

app/controllers/video_interview/questions_controller.rb
class VideoInterview::QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_action
  before_action :set_video_interview_question, only: [:show, :edit, :update, :destroy]

  # GET /video_interview/questions
  # GET /video_interview/questions.json
  def index
    @video_interview_questions = VideoInterview::Question.page(params[:page])
  end

  # GET /video_interview/questions/1
  # GET /video_interview/questions/1.json
  def show
  end

  # GET /video_interview/questions/new
  def new
    @video_interview_question = VideoInterview::Question.new
  end

  # GET /video_interview/questions/1/edit
  def edit
  end

  # POST /video_interview/questions
  # POST /video_interview/questions.json
  def create
    @video_interview_question = VideoInterview::Question.new(video_interview_question_params)

    respond_to do |format|
      if @video_interview_question.save
        flash[:success] = t("resources.video_interview.question.create_success")
        format.html { redirect_to video_interview_questions_path }
        format.json { render :show, status: :created, location: @video_interview_question }
      else
        format.html { render :new }
        format.json { render json: @video_interview_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_interview/questions/1
  # PATCH/PUT /video_interview/questions/1.json
  def update
    respond_to do |format|
      if @video_interview_question.update(video_interview_question_params)
        flash[:success] = t("resources.video_interview.question.update_success")
        format.html { redirect_to video_interview_questions_path }
        format.json { render :show, status: :ok, location: @video_interview_question }
      else
        format.html { render :edit }
        format.json { render json: @video_interview_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_interview/questions/1
  # DELETE /video_interview/questions/1.json
  def destroy
    @video_interview_question.destroy
    respond_to do |format|
      format.html { redirect_to video_interview_questions_url, notice: t("resources.video_interview.question.destroy_success") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_interview_question
      @video_interview_question = VideoInterview::Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_interview_question_params
      params.require(:video_interview_question).permit(:content)
    end
    
    def authorize_action
      render 'errors/403', status: 403, layout: 'application' unless current_user.can?(:admin)
    end
end

app/controllers/video_interview/stages_controller.rb
class VideoInterview::StagesController < Stage::BasesController
  private
    def authorize_action
      unless has_permission?
        render 'errors/403', status: 403, layout: 'application'
      end
    end

    def has_permission?(stage=nil)
      current_user.can?(:admin, @stage || stage) ||
      current_user.can?(VideoInterview::Stage.to_s.tableize.to_sym, @course) ||
      current_user.can?(:admin, VideoInterview::Stage)
    end
end

app/helpers/video_interview/answers_helper.rb
module VideoInterview::AnswersHelper
  def show_time_limit(answer)
    ret = ""
    if answer.time_limit / 60 > 0
      if answer.time_limit / 60 == 1
        ret = "un minuto "
      else
        ret = (answer.time_limit / 60).to_s + " minutos "
      end
    end

    if answer.time_limit % 60 != 0
      if answer.time_limit % 60 == 1
        ret +=  "un segundo "
      else
        ret += (answer.time_limit % 60).to_s + " segundos "
      end
    end
    ret
  end
end

app/helpers/video_interview/questions_helper.rb
module VideoInterview::QuestionsHelper
end

app/helpers/video_interview/stage_helper.rb
module VideoInterview::StageHelper
  class << self
    def html_preview(view, video_interview_stage)
      return "" if video_interview_stage.nil?

      message = view.t('video_interview.stage.title')

      link = view.link_to(
        message,
        view.polymorphic_path([video_interview_stage.enrollment.course,video_interview_stage]),
        class: 'btn-link'
      )
      html = <<-HTML
      <div>
        #{link}
      </div>
      HTML

      html.html_safe
    end
  end
end

app/views/video_interview/questions/_form.html.slim
= form_for @video_interview_question do |f|

  .form-group
    = f.label :content
    = f.text_field :content, class: 'form-control', autofocus: true, required: field_required?(f, :content)
  
  .form-group
    .row
      .col-xs-12.col-md-3
        = f.submit class: "btn btn-block btn-success"

app/views/video_interview/questions/edit.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = t("resources.generals.labels.editing") + ' ' + VideoInterview::Question.model_name.human
.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'common/info_panel', locals: { main_info: 'lorem', view_more: true, detail_info: 'lorem' }
          = render partial: 'form'

          .row
            .col-xs-12.col-md-3.padding-bottom-10-px 
              = link_to t("resources.generals.actions.show"), @video_interview_question, class: "btn btn-block btn-success btn-inverted"
            .col-xs-12.col-md-3
              = link_to t("resources.generals.actions.back"), video_interview_questions_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/video_interview/questions/index.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-sm-9.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = VideoInterview::Question.model_name.human(count: :other) + " " +  VideoInterview::Stage.model_name.human(count: :other)
        .col-xs-6.col-sm-3.col-md-2
          .margin-top-10-px
            .col-xs-12
              = link_to t("resources.generals.labels.new.m") + ' ' + VideoInterview::Question.model_name.human, new_video_interview_question_path , class: "btn btn-block btn-success"

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'common/info_panel', locals: { main_info: 'video_interview', view_more: true, detail_info: 'video_interview' }
          table.table.table-bordered.table-hover
            thead
              tr
                th style='vertical-align: middle' width='86%' = VideoInterview::Question.human_attribute_name(:content)
                th style='vertical-align: middle' colspan="3"

            tbody
              - @video_interview_questions.each do |video_interview_question|
                tr
                  td.small style='vertical-align: middle' width="36%" = link_to video_interview_question.content , video_interview_question, class: "text-base"

                  td style='vertical-align: middle'
                    = link_to t("resources.generals.actions.edit"), edit_video_interview_question_path(video_interview_question), class: "btn btn-block btn-primary btn-sm"

                  td style='vertical-align: middle'
                    = link_to t("resources.generals.actions.destroy"), video_interview_question, data: {:confirm => (t("resources.generals.actions.destroy_confirm") + ' ' + video_interview_question.content + ' ?')}, :method => :delete, class: "btn btn-block btn-danger btn-sm"


          = paginate @video_interview_questions

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/video_interview/questions/new.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = t("resources.generals.labels.new.f") + ' ' + VideoInterview::Question.model_name.human

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: 'form'

          .row
            .col-xs-12.col-md-3
              = link_to t("resources.generals.actions.back"), video_interview_questions_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"

app/views/video_interview/questions/show.html.slim
-content_for :subheader do
  .row
    .col-xs-12
      .col-xs-12.padding-bottom-10-px.__white-background.__with_shadow
        .col-xs-6.col-md-10
          h3.text-success
            span.glyphicon.glyphicon-retweet
            | &nbsp;
            | &nbsp;
            = @video_interview_question.content.capitalize

.container
  .row
    .col-md-9
      .col-md-12.padding-bottom-20-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          label = t("resources.generals.labels.name")
          p = @video_interview_question.content

          .row
            .col-xs-12.col-md-2.padding-bottom-10-px 
              = link_to t("resources.generals.actions.edit"), edit_video_interview_question_path(@video_interview_question), class: "btn btn-block btn-primary"
            .col-xs-12.col-md-2
              = link_to t("resources.generals.actions.back"), video_interview_questions_path, class: "btn btn-block btn-primary btn-inverted"

    .col-md-3
      .col-md-12.padding-bottom-10-px.__white-background.__with_shadow.padding-top-20-px
        .col-md-12
          = render partial: "scaffolds/scaffolds_list"